# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bennie Mosher
email: benniemosher@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benniemosher.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: benniemosher
github_username: benniemosher

# Build settings
markdown: kramdown
theme: plainwhite
plugins:
  - jekyll-feed
  - jekyll-seo-tag

plainwhite:
  name: Bennie Mosher
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  analytics_id: "UA-43449336-1"
  disqus_shortname: "benniemosher-1"
  sitemap: true

  navigation:
    - title: About
      url: "/about"
    - title: Resume
      url: "/resume"

  social_links:
    twitter: benniemosher
    github: benniemosher
    linkedIn: in/benniemosher # format: locale/username
    rss: rss

collections:
  - jobs
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
