title: Bennie Mosher
email: benniemosher@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Father. Husband. Problem Solver. Software Engineer.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benniemosher.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: benniemosher
github_username: benniemosher

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier

date_format: "%b %-d, %Y"
#   analytics_id: "UA-43449336-1"
#   disqus_shortname: "benniemosher-1"

collections:
  - jobs

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

jekyll-minifier:
  uglifier_args:
    harmony: true

feed:
  tags: false
