title: Bennie Mosher
email: benniemosher@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benniemosher.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: benniemosher
github_username: benniemosher

# Build settings
markdown: kramdown
theme: plainwhite
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-menus

plainwhite:
  name: Bennie Mosher
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  analytics_id: "UA-43449336-1"
  disqus_shortname: "benniemosher-1"
  sitemap: true
  logo: https://www.gravatar.com/avatar/cfa63d2ac1df40f47b3855327d3a0924?s=200

  social_links:
    twitter: benniemosher
    github: benniemosher
    linkedIn: in/benniemosher # format: locale/username
    rss: rss

collections:
  - jobs

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"
