backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: assets/img/uploads

collections:
  - name: posts
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          default:
            ["Uncategorized", "TDD", ".dotfiles", "Vim", "Rails", "Learning"],
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: jobs
    label: "Jobs"
    folder: "_jobs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Duration", name: "duration", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Hide", name: "hide_from_sitemap", widget: "boolean" }
