---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@main"
    permissions:
      contents: write

  heimdallr:
    needs: release
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@main"
    permissions:
      issues: write
      pull-requests: write
    secrets: inherit
    with:
      enable_slack: ${{ github.event_name != 'pull_request' }}
      enable_comment_on_pr: ${{ github.event_name == 'pull_request' }}
      comment_identifier: "<!-- heimdallr_release_version_comment -->"
      comment_content: "## :rocket: Next Release Version\n\nThe next semantic version for this PR will be: **${{ needs.release.outputs.next_version }}**"
      slack_message: "The project <https://github.com/${{ github.repository }}|${{ github.repository }}> just released version <https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.next_version }}|${{ needs.release.outputs.next_version }}>."
